//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUON()
        {
            this.CHITIETPHIEUMUONs = new HashSet<CHITIETPHIEUMUON>();
        }
    
        public string MaPhieuMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime NgayTraDukien { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<double> TienPhatTong { get; set; }
        public Nullable<bool> DaTra { get; set; }
        public Nullable<int> MaTaiKhoai { get; set; }
        public string MaTheDocGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUMUON> CHITIETPHIEUMUONs { get; set; }
        public virtual TAIKHOANTHUTHU TAIKHOANTHUTHU { get; set; }
        public virtual THEDOCGIA THEDOCGIA { get; set; }
    }
}
