//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH_PHIEUMUONTRA
    {
        public int MaMuonTra { get; set; }
        public string MaSach { get; set; }
        public string MaPhieuMuon { get; set; }
        public Nullable<System.DateTime> NgayTraThat { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual PHIEUMUONTRA PHIEUMUONTRA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
