//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANDOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOANDOCGIA()
        {
            this.THEDOCGIAs = new HashSet<THEDOCGIA>();
        }
    
        public int MaTaiKhoaiDocGia { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string TrangThai { get; set; }
        public string MaDocGia { get; set; }
        public int MaTaiKhoai { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual TAIKHOANTHUTHU TAIKHOANTHUTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEDOCGIA> THEDOCGIAs { get; set; }
    }
}
