//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANTHUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOANTHUTHU()
        {
            this.DOCGIAs = new HashSet<DOCGIA>();
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
            this.TAIKHOANDOCGIAs = new HashSet<TAIKHOANDOCGIA>();
            this.THEDOCGIAs = new HashSet<THEDOCGIA>();
        }
    
        public int MaTaiKhoai { get; set; }
        public string TenTaiKhoai { get; set; }
        public string MatKhau { get; set; }
        public string TrangThai { get; set; }
        public string MaThuThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCGIA> DOCGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOANDOCGIA> TAIKHOANDOCGIAs { get; set; }
        public virtual THUTHU THUTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEDOCGIA> THEDOCGIAs { get; set; }
    }
}
