//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEDOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEDOCGIA()
        {
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
        }
    
        public string MaTheDocGia { get; set; }
        public System.DateTime NgayTheDuocTao { get; set; }
        public System.DateTime NgayTheDuocGiaHan { get; set; }
        public string TenDocGia { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public Nullable<int> MaTaiKhoaiDocGia { get; set; }
        public Nullable<int> MaTaiKhoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
        public virtual TAIKHOANDOCGIA TAIKHOANDOCGIA { get; set; }
        public virtual TAIKHOANTHUTHU TAIKHOANTHUTHU { get; set; }
    }
}
