//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUON()
        {
            this.SACH_PHIEUMUON = new HashSet<SACH_PHIEUMUON>();
        }
    
        public string MaPhieuMuon { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public int SoLuongSachMuon { get; set; }
        public System.DateTime NgayTra { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public string MaThuThu { get; set; }
        public string MaDocGia { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual THUTHU THUTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH_PHIEUMUON> SACH_PHIEUMUON { get; set; }
    }
}
