//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH_PHIEUMUON
    {
        public int MaSachPhieuMuon { get; set; }
        public string MaSach { get; set; }
        public string MaPhieuMuon { get; set; }
    
        public virtual PHIEUMUON PHIEUMUON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
